server:
  port: 8080  # Application will run on port 8080

build:
  version: "6.0"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb  # MySQL running on port 3307, using loansdb
    username: root                            # MySQL username
    password: root                            # MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL JDBC driver class
    hikari:
      maximum-pool-size: 10                    # Connection pool size (optional tuning)
  sql:
    init:
      mode: always                          # Ensures SQL initialization runs
  jpa:
    show-sql: true                            # Logs SQL queries in the console
    hibernate:
      ddl-auto: update                        # Automatically updates schema (optional)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # Adjust dialect based on MySQL version

  config:
    import: "optional:configserver:http://localhost:8071/"  # External config server

  rabbitmq:
    host: "localhost"                         # RabbitMQ settings
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"                          # Exposes all actuator endpoints
