server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/loansdb
    username: root
    password: root
    sql:
      init:
        mode: always
  jpa:
    show-sql: true

  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"