spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      uri: http://localhost:8071
      server:
        native:
          search-locations: "classpath:/config"
        # search-locations: "file:///Users//eazybytes//Documents//config"

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
server:
  port: 8071